apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: blog
deploy:
  kubectl:
    manifests:
      - infra/k8s/client-depl.yaml
      - infra/k8s/comments-depl.yaml
      - infra/k8s/event-bus-depl.yaml
      - infra/k8s/moderation-depl.yaml
      - infra/k8s/ingress-srv.yaml
      - infra/k8s/post-depl.yaml
      - infra/k8s/query-depl.yaml
build:
  local:
    push: false
  artifacts:
    - image: adnansabbir/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: adnansabbir/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: adnansabbir/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: adnansabbir/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: adnansabbir/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
    - image: adnansabbir/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '*.js'
            dest: .
